name: Publish Docs
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧 
        run: npx @compodoc/compodoc -c .compodocrc.json -d docs src

      - name: Set cname
        run: echo "docs.socfony.com" > docs/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
