# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Build 🔧
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx @compodoc/compodoc -c .compodocrc.json -d docs src
    - name: Set cname 🔗
    - run: echo "docs.socfony.com" > docs/CNAME
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      BRANCH: gh-pages
      FOLDER: docs
      CLEAN: true
